parameters:
    tcpdf_class:  Io\TcpdfBundle\Helper\Tcpdf
  
services:
  io_tcpdf:
    class:  %tcpdf_class%
    arguments:
      orientation: P
      unit:        mm
      format:      A4
      unicode:     true
      encoding:    UTF-8
      diskcache:   false
      pdfa:        false
